name: Deploy to Cloud Run

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" > backend/.env
          echo "MAP_API_KEY=$MAP_API_KEY" >> backend/.env
      - name: Create Credentials file
        env:
          FIREBASE_AUTH: ${{secrets.FIREBASE_AUTH }}
        run: echo "$FIREBASE_AUTH" > backend/firebase_auth.json
        
      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      - uses: 'google-github-actions/setup-gcloud@v1'

      - run: gcloud auth configure-docker us-east5-docker.pkg.dev

        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t us-east5-docker.pkg.dev/travelgpt-3d352/travelgpt/travelgpt:latest ./backend

      - name: Push Docker image
        run: docker push us-east5-docker.pkg.dev/travelgpt-3d352/travelgpt/travelgpt:latest

      - name: Deploy to Cloud Run
        run: gcloud run deploy travelgpt --image us-east5-docker.pkg.dev/travelgpt-3d352/travelgpt/travelgpt:latest --region us-east5 --platform managed

